### PR TITLE
Define NativeFile

### LINKED ISSUE #53: Add support for conditionally building support for each object format
Goblin has a set of features that let you choose which formats are supported. It would be nice if we could have the same for 'object'. This can cut down on code size in situations where you only need to support the native format of the platform you're running on. An example use case for this is backtrace-rs, additionally we'd like this for use in the profiler in Gecko.

### PR DESCRIPTION
**Pull request by philipc**
Fixes #53 

I looked into also adding feature flags, but didn't for two reasons
- we would still have to enable all goblin features anyway for `peek_bytes`
- the cfg attributes were getting messy, eg due to unused lifetimes on enums (maybe it would have been better to leave the lifetimes on wasm after all, but that wasn't the only case)

### CODE REVIEW

**Comment by fitzgen** [comment]
> I looked into also adding feature flags, but didn't for two reasons

I think as long as we aren't too tricky for the linker's `--gc-sections` and/or the compiler's DCE, then we are good. IIUC, `enum File` is too tricky, in that sense.

File: src/lib.rs [hunk 1]
```diff
@@ -62,6 +62,22 @@ pub use wasm::*;
...
+#[cfg(target_os = "macos")]
+pub type NativeFile<'data> = MachOFile<'data>;
+
+/// The native object file for the target platform.
+#[cfg(target_os = "windows")]
+pub type NativeFile<'data> = PeFile<'data>;
+
+/// The native object file for the target platform.
+#[cfg(all(feature = "wasm", target_arch = "wasm32"))]
+pub type NativeFile<'data> = WasmFile<'data>;
```
Comment (fitzgen) [inline src/lib.rs]: This might be nicer with `cfg-if`, but that is definitely not a blocker to landing anything :-P

Comment (fitzgen) [reply src/lib.rs]: (Because cfg-if will enforce that these cases are exclusive)
